package entity;
// Generated Nov 18, 2024 7:37:15 AM by Hibernate Tools 4.3.1



/**
 * TbMbrg generated by hbm2java
 */
public class TbMbrg  implements java.io.Serializable {


     private String kodeBarang;
     private String pelanggan;
     private String jenisBarang;
     private int stok;
     private int harga;

    public TbMbrg() {
    }

    public TbMbrg(String kodeBarang, String pelanggan, String jenisBarang, int stok, int harga) {
       this.kodeBarang = kodeBarang;
       this.pelanggan = pelanggan;
       this.jenisBarang = jenisBarang;
       this.stok = stok;
       this.harga = harga;
    }
   
    public String getKodeBarang() {
        return this.kodeBarang;
    }
    
    public void setKodeBarang(String kodeBarang) {
        this.kodeBarang = kodeBarang;
    }
    public String getPelanggan() {
        return this.pelanggan;
    }
    
    public void setPelanggan(String pelanggan) {
        this.pelanggan = pelanggan;
    }
    public String getJenisBarang() {
        return this.jenisBarang;
    }
    
    public void setJenisBarang(String jenisBarang) {
        this.jenisBarang = jenisBarang;
    }
    public int getStok() {
        return this.stok;
    }
    
    public void setStok(int stok) {
        this.stok = stok;
    }
    public int getHarga() {
        return this.harga;
    }
    
    public void setHarga(int harga) {
        this.harga = harga;
    }




}


